# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-21 05:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20170613_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='first_visit',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 5, 24, 4, 842775)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 5, 24, 25, 304036)),
            preserve_default=False,
        ),
    ]
